### ISSUE TITLE
Update equation in README

### ISSUE THREAD

**Issue by mcfarljm** [dwave-examples/mutual-information-feature-selection#13]
The usage of `k` and summation subscripting does not seem to be very clear.  Is there a specific meaning to the subscript of the second summation, `j \in k | i`?  I am not sure exactly what this means.  It may be more clear to replace the equation directly with the one given in the Nguyen et al. reference, Eq. (17), which uses a much more straightforward subscripting.

![image](https://user-images.githubusercontent.com/626029/108922414-fb5ef200-75eb-11eb-8019-fe28a90b7477.png)

**Comment by mcfarljm** [comment]
@JoelPasvolsky Do you have any thoughts on this?  In addition to potential confusion about the `j \in k | i` notation in the second summation noted above, I'm not sure that the equation is actually correct.  As written, the first summation shows the mutual information between Xi and Y being summed from 1 to n.  This is a sum over all features, whereas the calculation that we want to optimize should sum mutual information over only the k selected features, not all n features.  See the suggested equation above for how this could be expressed.

My recommendation is to replace the equation in the README with the one above.  Wanted to check with you first, though, as the current equation also appears in the jupyter notebook under Leap online resources.

**Comment by JoelPasvolsky** [comment]
@mcfarljm, I think the current formulation came from approximating conditional independence, where j belongs to a subset of size k but without element i is shown as `j \in k | i`.  A more explicit notation might be `j \in k, j!=i`.
I think we do need the summation of n features, and only the internal (second) summation is over k selected features. 
Adding @pau557 for comment too.

**Comment by mcfarljm** [comment]
> 
> 
> I think we do need the summation of n features, and only the internal (second) summation is over k selected features.
> Adding @pau557 for comment too.

Not sure I agree.  The first summation is only over the selected features.  See the equation I included above, which shows that it is summing over Xi in the set S, where S is the set of features we are selecting.  In the QUBO formulation, the sum is over n but there is a binary variable in front of each mutual information coefficient.  So I think that for the equation to be correct, it either needs to use a subset notation (as above), or the summation over n needs to include the binary indicator variables.

**Comment by JoelPasvolsky** [comment]
Yes, for the summation you're right about the difference between the MIQUBO formulation and the QUBO with it's binary variable. The first summation probably should be on s (the second on s with i).

**Comment by mcfarljm** [comment]
I'm also not sure about writing something like `j \in k`.  k is not a set, it is an integer.  What does `j \in k` mean?  Does it mean something like `j=1...k`?  That wouldn't be right in this context either, because we're trying to select k features, but the k features that we select are not necessarily those with indices 1...k.  That is why it looks to me that the objective needs to be expressed either in terms of sets (as in the original paper) or in terms of binary indicator variables.  I'm also unclear about what is meant by "arg max k", because that seems to indicate that the goal is to find the value of k that maximizes the objective function, but that is not the case.

**Comment by pau557** [comment]
>Not sure I agree. The first summation is only over the selected features. See the equation I included above, which shows that it is summing over Xi in the set S, where S is the set of features we are selecting. In the QUBO formulation, the sum is over n but there is a binary variable in front of each mutual information coefficient. So I think that for the equation to be correct, it either needs to use a subset notation (as above), or the summation over n needs to include the binary indicator variables.

I agree with @mcfarljm.

I also think that using `k` to denote a subset instead of an index (like `i` and `j`) is a source of confusion.

Below is another way of presenting this equation, but showing the Nguyen et al formulation is a better idea.

![image](https://user-images.githubusercontent.com/31051788/109203185-b3111280-7758-11eb-9931-9586de4737e0.png)

**Comment by pau557** [comment]
I believe that @akoszegi also pointed at some confusion regarding this some time ago

**Comment by JoelPasvolsky** [comment]
@mcfarljm, you'd be changing C to Y, right, and leaving implicit that `i!=j` right? That should not be confusing if it's not explicit, I think.

**Comment by mcfarljm** [comment]
> 
> 
> @mcfarljm, you'd be changing C to Y, right, and leaving implicit that `i!=j` right? That should not be confusing if it's not explicit, I think.

It may be best to use Pau's equation (no confusion about `i!=j`), but I think I would prefer to drop the `1/|S|` part for simplicity and to match what is used in the code.

**Comment by JoelPasvolsky** [comment]
The `1/|s|` will be confusing but I also worry that not all users will recognize the `\i`. Maybe `j \in S, j!=i` would be better?

**Comment by mcfarljm** [comment]
How about this:
![image](https://user-images.githubusercontent.com/626029/109530430-8ec07900-7a6b-11eb-90e3-f3bcca9e0ef0.png)
